// config.bin - 15:37:57 04/14/21, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ctab_irl_main {
		name = "main";
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.88;
		requiredAddons[] = {};
		author = AUTHOR;
		version = 0.1.0.0;
		versionStr = 0.1.0.0;
		versionAr[] = {0, 1, 0, 0};
	};
};
