// config.bin - 15:37:25 04/14/21, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ctab_core {
		name = "core";
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.88;
		requiredAddons[] = {"ctab_main"};
		author = AUTHOR;
		version = 2.5.0.0;
		versionStr = 2.5.0.0;
		versionAr[] = {2, 5, 0, 0};
	};
};

class Extended_PreStart_EventHandlers {
	class ctab_core {
		init = "call compile preprocessFileLineNumbers '\z\ctab\addons\core\XEH_preStart.sqf'";
	};
};

class Extended_PreInit_EventHandlers {
	class ctab_core {
		init = "call compile preprocessFileLineNumbers '\z\ctab\addons\core\XEH_preInit.sqf'";
	};
};

class Extended_PostInit_EventHandlers {
	class ctab_core {
		init = "call compile preprocessFileLineNumbers '\z\ctab\addons\core\XEH_postInit.sqf'";
		clientInit = "call compile preprocessFileLineNumbers '\z\ctab\addons\core\XEH_postInitClient.sqf'";
		serverInit = "call compile preprocessFileLineNumbers '\z\ctab\addons\core\XEH_postInitServer.sqf'";
	};
};

class CfgVehicles {
	class Man;	
	
	class CAManBase : Man {
		class ACE_SelfActions {
			class cTab_Interact {
				displayName = "$STR_ctab_core_aceMenu";
				condition = "true";
				exceptions[] = {"isNotInside", "isNotSitting"};
				statement = "";
				insertChildren = "_this call ctab_core_fnc_aceSelfActions";
				priority = 0.1;
			};
		};
	};
};
class RscText;	
class IGUIBack;	
class RscEdit;	
class RscCombo;	
class RscCheckbox;	
class RscButton;	

class cTab_TechnicalData_dlg {
	idd = 1775148;
	onLoad = "_this call ctab_core_fnc_onTechnicalDataOpen;";
	onUnload = "_this call ctab_core_fnc_onTechnicalDataClose;";
	objects[] = {};
	
	class controlsBackground {
		class Frame : IGUIBack {
			idc = 9935;
			x = 2.5 * (0.025) + (0);
			y = 7.5 * (0.04) + (0);
			w = 35 * (0.025);
			h = 10 * (0.04);
			colorBackground[] = {0, 0, 0, 0.5};
		};
	};
	
	class controls {
		class Title : RscText {
			idc = 8734;
			text = "$STR_ctab_core_techData";
			x = 3.5 * (0.025) + (0);
			y = 8.5 * (0.04) + (0);
			w = 33 * (0.025);
			h = 1 * (0.04);
		};
		
		class CallsignLabel : RscText {
			idc = 8735;
			text = "$STR_ctab_core_callSign";
			x = 3.5 * (0.025) + (0);
			y = 10.5 * (0.04) + (0);
			w = 11 * (0.025);
			h = 1 * (0.04);
		};
		
		class Callsign : RscEdit {
			idc = 9135;
			text = "";
			x = 15.5 * (0.025) + (0);
			y = 10.5 * (0.04) + (0);
			w = 21 * (0.025);
			h = 1 * (0.04);
		};
		
		class OkButton : RscButton {
			idc = 1;
			text = $STR_DISP_OK;
			x = 28.5 * (0.025) + (0);
			y = 16 * (0.04) + (0);
			w = 8 * (0.025);
			h = 1 * (0.04);
		};
		
		class CancelButton : RscButton {
			idc = 2;
			text = $STR_DISP_CANCEL;
			x = 3.5 * (0.025) + (0);
			y = 16 * (0.04) + (0);
			w = 8 * (0.025);
			h = 1 * (0.04);
		};
	};
};
