// config.bin - 15:38:03 04/14/21, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ctab_irl_tacmap {
		name = "tacmap";
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.88;
		requiredAddons[] = {"ctab_irl_main"};
		author = AUTHOR;
		version = 0.1.0.0;
		versionStr = 0.1.0.0;
		versionAr[] = {0, 1, 0, 0};
	};
};

class Extended_PreStart_EventHandlers {
	class ctab_irl_tacmap {
		init = "call compile preprocessFileLineNumbers '\z\ctab_irl\addons\tacmap\XEH_preStart.sqf'";
	};
};

class Extended_PreInit_EventHandlers {
	class ctab_irl_tacmap {
		init = "call compile preprocessFileLineNumbers '\z\ctab_irl\addons\tacmap\XEH_preInit.sqf'";
	};
};

class Extended_PostInit_EventHandlers {
	class ctab_irl_tacmap {
		init = "call compile preprocessFileLineNumbers '\z\ctab_irl\addons\tacmap\XEH_postInit.sqf'";
	};
};
