// config.bin - 15:38:12 04/14/21, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ctab_main {
		name = "main";
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.88;
		requiredAddons[] = {};
		author = "cTab Authors";
		authors[] = {"Gundy", "Riouken", "Raspu", "GrueArbre"};
		authorUrl = "https://github.com/jetelain/cTab";
		version = 2.5.0.0;
		versionStr = 2.5.0.0;
		versionAr[] = {2, 5, 0, 0};
	};
};
